[2018-08-28 14:32:23,111]-result.py:58-ERROR - Index error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 55, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 43, in _get
    is_login = bool(self.user)
AttributeError: 'Index' object has no attribute 'user'

[2018-08-28 14:50:50,178]-result.py:58-ERROR - Index error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 55, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 49, in _get
    return self.render_html('app/index.html', index=index, auth=auth)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_index_html", line 25, in render_body
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined

[2018-08-28 15:27:07,631]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 420, in request_unifiedorder
    'openid': self.user.openid,
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'openid'

[2018-08-28 15:27:58,856]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 406, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 402, in get_sign
    return check.MD5(string).upper()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/utils/check.py", line 63, in MD5
    md5.update(string.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 30: ordinal not in range(128)

[2018-08-28 15:28:45,844]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 433, in request_unifiedorder
    resp = requests.post(constant.WECHAT_UNIFIED_ORDER, data=xml.encode('utf-8'),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 11: ordinal not in range(128)

[2018-08-28 15:29:56,857]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 406, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 400, in get_sign
    string = '&'.join(['{}={}'.format(k, kwargs[k]) for k in keys if k != 'appkey'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

[2018-08-28 15:31:43,025]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 406, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 400, in get_sign
    string = '&'.join(['{0}={1}'.format(k, kwargs[k]) for k in keys if k != 'appkey'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

[2018-08-28 15:33:06,594]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 432, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 407, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 401, in get_sign
    string = '&'.join(['{0}={1}'.format(k, kwargs[k]) for k in keys if k != 'appkey'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

[2018-08-28 15:34:10,127]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 432, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 407, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 402, in get_sign
    string = "{0}&key={1}".format(string, constant.WBC['KEY'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-33: ordinal not in range(128)

[2018-08-28 15:35:17,522]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 406, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 402, in get_sign
    return check.MD5(string).upper()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/utils/check.py", line 63, in MD5
    md5.update(string)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-33: ordinal not in range(128)

[2018-08-28 15:36:02,215]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 406, in get_xml
    kwargs['sign'] = self.get_sign(kwargs)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 402, in get_sign
    return check.MD5(string).upper()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/utils/check.py", line 63, in MD5
    md5.update(string.decode('utf-8'))
  File "/Users/shuai.chen/pyenv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-33: ordinal not in range(128)

[2018-08-28 15:37:00,886]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 431, in request_unifiedorder
    xml = self.get_xml(unifiedorder_request)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 407, in get_xml
    xmls = ['<{0}>{1}</{0}>'.format(k, v) for k, v in kwargs.iteritems()]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

[2018-08-28 15:37:45,306]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 344, in _post
    if data['code'] == alert.SUCCESS:
TypeError: 'Result' object has no attribute '__getitem__'

[2018-08-28 16:52:30,750]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 420, in request_unifiedorder
    'openid': self.user.openid,
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'openid'

[2018-08-28 16:52:38,128]-result.py:58-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 53, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 342, in _post
    data = self.request_unifiedorder(order_code, amount)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 420, in request_unifiedorder
    'openid': self.user.openid,
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'openid'

